#!/usr/bin/env bash
#Configuration for haproxy load balancer

apt-get update
apt-get -y install haproxy

BACKEND_CONFIG=\
"
backend allServers
	timeout connect 10s
	timeout server  10s
	balance roundrobin
	mode http
	server 5821-web-01 54.163.21.212:80 check
	server 5821-web-02 34.236.158.180:80 check
"
FRONTEND_CONFIG=\
"
frontend www
	mode http
	timeout client 10s
	bind *:80
	default_backend allServers
"
echo -e "$FRONTEND_CONFIG" >> /etc/haproxy/haproxy.cfg
echo -e "$BACKEND_CONFIG" >> /etc/haproxy/haproxy.cfg
service haproxy restart
