#!/usr/bin/env bash
# installing and config nginx

apt-get update
apt-get -y install nginx

# adding an html page
echo "Holberton School" >

# checking if service is running
state=$(pgrep nginx)
if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
